name: Scrape Seek

on:
  workflow_dispatch:   # so you (or n8n) can trigger it
  schedule:
    - cron: "0 21 * * *"   # run daily at 7am AEST (21:00 UTC)

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing CSV back into repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python seek_scraper.py

      - name: Commit CSV back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -f "seek_jobs_24h.csv" ]; then
            git add seek_jobs_24h.csv
            git commit -m "Update seek_jobs_24h.csv [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "⚠️ No CSV file generated by script"
          fi
