name: Run Seek Scraper

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch: {}      # manual run button

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps + browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          HEADLESS: "true"                  # force headless in CI
          KEYWORD: "Senior Insight Analyst" # override if you like
          MIN_SALARY: "150000"
          LISTING_DATE: "1"                 # last 24h
          CSV_PATH: "seek_jobs_24h.csv"
        run: |
          python seek_scraper.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: seek_jobs_csv
          path: seek_jobs_24h.csv
