name: Scrape Seek (headed via Xvfb)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 20-23 * * *"
    - cron: "0 0-8 * * *"

permissions:
  contents: write

concurrency:
  group: seek-scraper
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { KEYWORD: "Senior Insight Analyst", MIN_SALARY: "150000", CSV_PATH: "seek_SIA_24h.csv" }
          - { KEYWORD: "ML AI Engineer",        MIN_SALARY: "0",       CSV_PATH: "seek_MLAI_24h.csv" }
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Playwright + Chromium + Xvfb)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run scraper under Xvfb (headed)
        env:
          HEADLESS: "false"
          KEYWORD: ${{ matrix.cfg.KEYWORD }}
          MIN_SALARY: ${{ matrix.cfg.MIN_SALARY }}
          LISTING_DATE: "1"
          CSV_PATH: ${{ matrix.cfg.CSV_PATH }}
        run: |
          xvfb-run -a --server-args='-screen 0 1920x1080x24' python seek_scraper.py
          ls -l $CSV_PATH

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cfg.CSV_PATH }}
          path: ${{ matrix.cfg.CSV_PATH }}

  persist:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all CSVs
        uses: actions/download-artifact@v4
        with:
          path: ./csvs

      - name: Move CSVs to repo root (or keep under /csvs if you prefer)
        run: |
          shopt -s globstar
          find ./csvs -type f -name "*.csv" -exec mv {} . \;

      - name: Commit CSVs back to repo (single atomic commit)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Update Seek CSVs [skip ci]" || echo "No changes to commit"
          git push
